import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { loadDashboardHarness } from './helpers/dashboard-harness.mjs';
const require = createRequire(import.meta.url);
const R = require('../app/fitness-records.js');
for (const activity_type of Object.keys(R.forms)) {
  const row = R.activity({id:'activity',activity_date:'2026-10-03',activity_type,name:'實際活動',metrics:{duration_minutes:'30.5',distance_km:'2.2'}});
  assert.equal(row.metrics.duration_minutes,30.5);
  assert.equal(row.metrics.intensity,null);
  assert.equal(row.exercises.length,0);
}
assert.throws(() => R.activity({activity_type:'hiking',activity_date:'2026-02-30',name:'登山'}));
assert.throws(() => R.activity({activity_type:'hiking',activity_date:'2026-10-03',name:'登山',metrics:{duration_minutes:60,elapsed_minutes:30}}));
assert.throws(() => R.numeric('Infinity','duration_minutes'));
assert.throws(() => R.numeric(2.5,'intensity'));
assert.equal(R.isRequest({request_id:'x',bundle:{daily:{id:'x'},workouts:[null]}}),false);
assert.equal(R.isRequest({request_id:'x',changes:[{kind:'activity',id:'x',operation:'create',expected_version:0,snapshot:{exercises:{}}}]}),false);
const strength=R.activity({activity_date:'2026-10-03',activity_type:'strength',name:'自由重訓',exercises:[{name:'Squat',weight_kg:'12.5',reps_by_set:'10/10/8'}]});
assert.deepEqual(strength.exercises,[{name:'Squat',weight_kg:12.5,reps_by_set:[10,10,8]}]);
assert.throws(() => R.activity({activity_date:'2026-10-03',activity_type:'strength',name:'重訓',exercises:[{name:'Squat',reps_by_set:'10/x'}]}));
const fitness={_entries:[{id:'daily',entry_date:'2026-10-03',bodyweight_kg:60,revision:1}],_workouts:[{id:'workout',daily_entry_id:'daily',workout_date:'2026-10-03',completed:true}],_activities:[{id:'activity',activity_date:'2026-10-03',name:'跑步',metrics:{duration_minutes:60},revision:1,updated_at:'2026-10-03T01:00:00Z'}],_versions:[],jessicaReview:{reviewed_at:'2026-10-03T02:00:00Z',evidence:{record_versions:[{kind:'activity',id:'activity',revision:1}]}}};
assert.deepEqual(R.stats(fitness,'2026-09-28','2026-10-03'),{exerciseDays:1,activityCount:1,planDays:1});
const request={request_id:'edit',created_at:'2026-10-03T03:00:00Z',changes:[{kind:'activity',id:'activity',operation:'revise',expected_version:1,snapshot:{metrics:{duration_minutes:30}},reason:'時間填錯'}]};
R.apply(fitness,request);
assert.equal(fitness._activities[0].metrics.duration_minutes,30);
assert.equal(fitness._versions[0].snapshot.metrics.duration_minutes,60);
assert.equal(R.needsReview(fitness),true);
fitness._reviewAcknowledgements=[{record_kind:'activity',record_id:'activity',revision:2}];
assert.equal(R.needsReview(fitness),false,'a source acknowledgement clears pending review without a new cycle');
fitness._reviewAcknowledgements=[];
assert.equal(fitness._activities[0].revision,2);
R.apply(fitness,{request_id:'withdraw',changes:[{kind:'activity',id:'activity',operation:'withdraw',expected_version:2,reason:'重複'}]});
assert.equal(R.stats(fitness,'2026-09-28','2026-10-03').activityCount,0);
R.apply(fitness,{request_id:'withdraw-daily',changes:[{kind:'daily',id:'daily',operation:'withdraw',expected_version:1,reason:'重複'}]});
assert.equal(R.activeWorkouts(fitness).length,0);
R.apply(fitness,request,true);
assert.equal(fitness._activities[0].revision,3,'stale offline drafts cannot overwrite current versions');

const {api,context,navigator,snapshot,setFetch}=loadDashboardHarness();
context.FitnessRecords=R;
api.state.data=api.emptyDashboard(); api.state.data.fitness.recordsV2Ready=true;
api.state.session={demo:true,user:{id:'demo'}};
const demoDate=context.DashboardFitnessAdapter.today();
api.state.data.fitness._activities=[{id:'demo-activity',activity_date:demoDate,name:'自由重訓',activity_type:'strength',metrics:{},exercises:[]}];
assert.equal(context.DashboardFitnessAdapter.getFitness().exerciseDaysThisWeek,'1','demo save refreshes the top exercise-day metric too');
api.state.data.fitness._activities[0].withdrawn=true;
assert.equal(context.DashboardFitnessAdapter.getFitness().exerciseDaysThisWeek,'0','demo withdrawal refreshes the top exercise-day metric too');
api.state.data=api.emptyDashboard(); api.state.data.fitness.recordsV2Ready=true;
api.state.session={user:{id:'owner'},access_token:'test'};
const queued={id:'request',row_id:'request',table:'fitness_records_v2',operation:'rpc',intent:'fitness-records/v2',owner_user_id:'owner',payload:{request_id:'request',changes:[{kind:'activity',id:'new',operation:'create',expected_version:0,snapshot:{id:'new',name:'羽球',activity_date:'2026-10-03',activity_type:'ball',metrics:{},exercises:[]}}]}};
api.state.pending=[queued];
const data=api.emptyDashboard();api.applyPendingOperations(data);
assert.equal(data.fitness._activities[0]._pending,true);
assert.equal(data.fitness._activities[0].name,'羽球');
api.state.session.user.id='other';
assert.equal(api.pendingForCurrentUser().length,0);
await assert.rejects(api.executeOperation(queued),/not owned/);
api.state.session.user.id='owner';api.state.config={supabaseUrl:'https://example.supabase.co',supabaseAnonKey:'test-anon-key-longer-than-twenty-characters'};api.state.supabaseReady=true;navigator.onLine=true;
let sent;
setFetch(async(url,options)=>{sent={url,body:JSON.parse(options.body)};return {ok:true,status:200,headers:{get:()=>null},text:async()=>JSON.stringify({request_id:'request'}),json:async()=>({request_id:'request'})};});
await api.executeOperation(queued);
assert.match(sent.url,/save_fitness_record_v2/);
assert.deepEqual(snapshot(sent.body),{p_request:queued.payload});
await assert.rejects(api.executeOperation({...queued,payload:{request_id:'different'}}),/Invalid Fitness v2/);
api.state.config.fitnessRecordsV2ReadOnly=true;
await assert.rejects(api.executeOperation(queued),/read-only/);
api.state.config.fitnessRecordsV2ReadOnly=false;
const beforeData=snapshot(api.state.data);
context.DashboardFitnessAdapter={getState:()=>api.state,getFitness:()=>api.state.data.fitness,cloud:()=>true,refreshToken:async()=>{},send:async()=>{api.state.session.user.id='different';return {request_id:'receipt'};},toast:()=>{},render:()=>{},enqueue:()=>{throw new Error('unexpected queue');},refresh:async()=>{throw new Error('unexpected refresh');}};
vm.runInContext(readFileSync(new URL('../app/fitness-records-ui.js',import.meta.url),'utf8'),context);
assert.equal(await context.FitnessRecordsUI.save({changes:queued.payload.changes}),'session_changed');
assert.deepEqual(snapshot(api.state.data),beforeData,'in-flight save cannot apply another owner data after session switch');
console.log('PASS Fitness v2 activity validation, versions, statistics, provenance exclusion and owned offline RPC');
